theme: jekyll-theme-cayman
title: My title
subtitlte: My subtitle
description: Experienced architect, development manager, full stack developer and hands-on leader with a successful record of delivering complex software projects for the financial services and energy sectors.
author: Joseph Simpson
twitter_username: simpsojo
