theme: jekyll-theme-cayman
title: [My title]
subtitle: [My subtitle]
description: [Experienced architect, development manager, full stack developer and hands-on leader with a successful record of delivering complex software projects for the financial services and energy sectors.]

social-network-links:
  email: "joseph.simpson@outlook.com"    
  github: joseph.simpson
  twitter: simpsojo
  linkedin: simpsojo
  stackoverflow: 1195908/joseph-simpson

share-links-active:
  twitter: true
  linkedin: true
  stackoverflow: true
